---
title: "Linear Models"
output: github_document
---

```{r setup, include=FALSE}
library(tidyverse)
library(p8105.datasets)
library(viridis)

knitr::opts_chunk$set(
	echo = TRUE,
	warning = FALSE,
	fig.width = 8, 
  fig.height = 6,
  out.width = "90%"
)

options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)
scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d
theme_set(theme_minimal() + theme(legend.position = "bottom"))
```

Load NYC Airbnb data.

```{r}
data("nyc_airbnb")
nyc_airbnb =
  nyc_airbnb %>% 
  mutate(stars = review_scores_location / 2) %>% 
  rename(
    borough = neighbourhood_group
  ) %>% 
  filter(borough != "Staten Island") %>% 
  select(price, stars, borough, neighbourhood, room_type)
```

fit a linear model: price = star + borough
```{r}
fit = lm(price ~ stars + borough, data = nyc_airbnb)

fit %>% 
  broom::tidy()  

fit %>% 
  broom::glance() 

```

```{r}
fit %>% 
  broom::tidy() %>% 
  mutate(
    term = str_replace(term, "borough", "Borough")
  ) %>% 
  select(term, estimate, p.value) %>% 
  knitr::kable(digits = 2)
```

change reference, the cat 1 in the data would be ref(default alphabetical)

```{r}
nyc_airbnb %>% 
  mutate(
    borough = fct_infreq(borough) # reorder by freq, most freq becomes cat 1
  ) %>% 
  lm(price ~ stars + borough, data = .) %>% 
  broom::tidy() %>% 
  mutate(
    term = str_replace(term, "borough", "Borough")
  ) %>% 
  select(term, estimate, p.value) %>% 
  knitr::kable(digits = 2)

```


```{r}
nyc_airbnb %>% 
  mutate(
    borough = fct_infreq(borough)
  ) %>% 
  lm(price ~ stars + borough, data = .) %>% 
  broom::glance() %>% # more info
  select(AIC) %>% 
  knitr::kable(digits = 2)
```

## Diagnostics

```{r}
modelr::add_residuals(nyc_airbnb, fit) %>% 
  ggplot(aes(x = stars, y=resid)) +
  geom_point()
```


```{r}
nyc_airbnb %>%  
modelr::add_residuals(fit) %>% 
  ggplot(aes(x = borough, y=resid)) +
  geom_violin()+
  ylim(-259, 250)
```

## Hypothesis testing

```{r}
fit_null = lm(price ~ stars, data=nyc_airbnb)
fit_alt = lm(price ~ stars + borough, data=nyc_airbnb)

anova(fit_null, fit_alt) %>% 
  broom::tidy()
```

## room type by borough
```{r}
fit = 
  nyc_airbnb %>% 
  lm(price ~ stars + borough * room_type, data=.)
  
fit %>% 
  broom::tidy()
```

## stratification

fit models by borough
```{r}
nyc_airbnb %>% 
  nest(df = -borough) %>% 
  mutate(
    models = map(.x = df, ~lm(price ~ stars + room_type, data = .x)),
    # take each nested df and fit a normal
    results = map(models, broom::tidy)
  ) %>% 
  select(borough, results) %>% 
  unnest(results)
```


